// Filters for categorical columns
export const parentGroup = ['Retail Trade', 'Manufacturing', 'Accommodation and Food Services',
'Professional, Scientific, and Technical Services',
'Transportation and Warehousing', 'Wholesale Trade', 'Information',
'Arts, Entertainment, and Recreation', 'Construction',
'Administrative and Support and Waste Management and Remediation Services',
'Finance and Insurance', 'Real Estate and Rental and Leasing',
'Health Care and Social Assistance',
'Agriculture, Forestry, Fishing and Hunting',
'Other Services (except Public Administration)',
'Public Administration', 'Educational Services']
export const subGroup = ['Motor Vehicle and Parts Dealers ',
'Computer and Electronic Product Manufacturing ',
'General Merchandise Stores ',
'Food Services and Drinking Places ',
'Professional, Scientific, and Technical Services ',
'Warehousing and Storage ',
'Furniture and Home Furnishings Stores ',
'Merchant Wholesalers, Durable Goods ',
'Motion Picture and Sound Recording Industries ',
'Food Manufacturing ', 'Electronics and Appliance Stores ',
'Accommodation ', 'Food and Beverage Stores ',
'Amusement, Gambling, and Recreation Industries ',
'Specialty Trade Contractors ', 'Miscellaneous Store Retailers ',
'Water Transportation ',
'Performing Arts, Spectator Sports, and Related Industries ',
'Administrative and Support Services ', 'Truck Transportation ',
'Merchant Wholesalers, Nondurable Goods ',
'Museums, Historical Sites, and Similar Institutions ',
'Credit Intermediation and Related Activities ',
'Clothing and Clothing Accessories Stores ',
'Sporting Goods, Hobby, Musical Instrument, and Book Stores ',
'Rental and Leasing Services ', 'Ambulatory Health Care Services ',
'Heavy and Civil Engineering Construction ',
'Animal Production and Aquaculture ', 'Repair and Maintenance ',
'Personal and Laundry Services', 'Real Estate ', 'Hospitals ',
'Scenic and Sightseeing Transportation ',
'Administration of Economic Programs ',
'Transportation Equipment Manufacturing ', 'Nonstore Retailers ',
'Building Material and Garden Equipment and Supplies Dealers ',
'Construction of Buildings ',
'Religious, Grantmaking, Civic, Professional, and Similar Organizations',
'Miscellaneous Manufacturing ', 'Gasoline Stations ',
'Educational Services ', 'Health and Personal Care Stores ',
'Machinery Manufacturing ',
'Insurance Carriers and Related Activities ',
'Furniture and Related Product Manufacturing ',
'Support Activities for Transportation ', 'Postal Service ',
'Waste Management and Remediation Services ',
'Nursing and Residential Care Facilities ',
'Transit and Ground Passenger Transportation ',
'Printing and Related Support Activities ',
'Rail Transportation ', 'Apparel Manufacturing ',
'Wholesale Electronic Markets and Agents and Brokers ',
'Securities, Commodity Contracts, and Other Financial Investments and Related Activities ',
'Justice, Public Order, and Safety Activities ',
'Monetary Authorities-Central Bank ', 'Telecommunications ',
'Crop Production ', 'Social Assistance ']
export const subSubGroup = ['New Car Dealers ',
'Analytical Laboratory Instrument Manufacturing ',
'Department Stores ', 'Full-Service Restaurants ',
'Outdoor Advertising', 'General Warehousing and Storage ',
'Other Scientific and Technical Consulting Services',
'Furniture Stores ',
'Other Construction Material Merchant Wholesalers ',
'Motion Picture Theaters (except Drive-Ins) ', 'Retail Bakeries ',
'Electronics Stores ', 'Hotels (except Casino Hotels) and Motels ',
'Supermarkets and Other Grocery (except Convenience) Stores ',
'Commercial Bakeries ', 'Fitness and Recreational Sports Centers ',
'Electrical Contractors and Other Wiring Installation Contractors',
'Office Supplies and Stationery Stores ',
'Inland Water Passenger Transportation ',
'Seafood Product Preparation and Packaging',
'Specialty Food Stores ', 'Limited-Service Restaurants ',
'Promoters of Performing Arts, Sports, and Similar Events with Facilities ',
'Travel Agencies', 'General Freight Trucking, Local ',
'Other Miscellaneous Nondurable Goods Merchant Wholesalers ',
'Used Merchandise Stores ', 'Food and Beverage Stores ',
'Industrial Machinery and Equipment Merchant Wholesalers ',
'Nature Parks and Other Similar Institutions',
'Drive-In Motion Picture Theaters ',
'Warehouse Clubs and Supercenters ',
'Snack and Nonalcoholic Beverage Bars ', 'Consumer Lending ',
"Men's Clothing Stores ", 'Recreational Vehicle Dealers ',
'Bowling Centers', 'Automobile Dealers ', 'Sporting Goods Stores ',
'Wine and Distilled Alcoholic Beverage Merchant Wholesalers ',
'Drinking Places (Alcoholic Beverages) ', 'General Rental Centers',
"Children's and Infants' Clothing Stores ", 'Tobacco Stores ',
'Amusement Arcades', 'Medical Laboratories ',
'General Line Grocery Merchant Wholesalers ',
'Other Clothing Stores ',
'Water and Sewer Line and Related Structures Construction ',
'Broilers and Other Meat Type Chicken Production ', 'Museums ',
'Consumer Electronics Repair and Maintenance ',
'All Other Miscellaneous Store Retailers (except Tobacco Stores) ',
'Family Clothing Stores ',
'Theater Companies and Dinner Theaters ',
'Beer, Wine, and Liquor Stores ',
'Motorcycle, Boat, and Other Motor Vehicle Dealers ',
"Women's Clothing Stores ", 'Pet and Pet Supplies Stores ',
'Farm Supplies Merchant Wholesalers ',
'All Other Personal Services ',
'Motor Vehicle Parts (Used) Merchant Wholesalers ',
'Lessors of Miniwarehouses and Self-Storage Units ',
'Used Car Dealers ', 'General Medical and Surgical Hospitals ',
'Veterinary Services ',
'Scenic and Sightseeing Transportation, Water', 'Car Washes ',
'Luggage and Leather Goods Stores ', 'Book Stores ',
'Offices of Real Estate Agents and Brokers',
'Appliance Repair and Maintenance ', 'Recreational Goods Rental ',
'Regulation and Administration of Transportation Programs ',
'All Other General Merchandise Stores ',
'Motorcycle, ATV, and All Other Motor Vehicle Dealers ',
'Software and Other Prerecorded Compact Disc, Tape, and Record Reproducing ',
'Truck, Utility Trailer, and RV (Recreational Vehicle) Rental and Leasing ',
'Other Motor Vehicle Parts Manufacturing',
'Other Direct Selling Establishments ', 'Land Subdivision ',
'Sewing, Needlework, and Piece Goods Stores ',
'Drycleaning and Laundry Services (except Coin-Operated) ',
'Hardware Stores ', 'Beauty Salons ',
'Performing Arts, Spectator Sports, and Related Industries ',
'Industrial Building Construction ',
'Gift, Novelty, and Souvenir Stores ',
'Golf Courses and Country Clubs',
'Tire and Tube Merchant Wholesalers ',
'Other Social Advocacy Organizations ',
'Hobby, Toy, and Game Stores ', 'Other Personal Care Services ',
'All Other Amusement and Recreation Industries ',
'Sporting and Recreational Goods and Supplies Merchant Wholesalers ',
'Motor Vehicle Supplies and New Parts Merchant Wholesalers ',
'Shoe Stores ', 'Jewelry and Silverware Manufacturing ',
'Independent Artists, Writers, and Performers ',
'Other Gasoline Stations ', 'Meat Markets ',
'Sports and Recreation Instruction ',
'Pet Care (except Veterinary) Services ', 'Offices of Lawyers',
'Offices of Physical, Occupational and Speech Therapists, and Audiologists ',
'Freestanding Ambulatory Surgical and Emergency Centers ',
'Offices of Physicians, Mental Health Specialists ',
'Offices of Physicians (except Mental Health Specialists) ',
'Nursery, Garden Center, and Farm Supply Stores ',
'New Single-Family Housing Construction (except For-Sale Builders) ',
'Offices of Dentists ', 'Automotive Glass Replacement Shops ',
'Offices of Physicians ',
'Electronic Shopping and Mail-Order Houses ',
'Civic and Social Organizations ',
'All Other Specialty Food Stores ', 'Clothing Stores ',
'Cosmetics, Beauty Supplies, and Perfume Stores ', 'Caterers',
'Recyclable Material Merchant Wholesalers ',
'All Other Miscellaneous General Purpose Machinery Manufacturing ',
'Direct Health and Medical Insurance Carriers ',
'Other Commercial and Service Industry Machinery Manufacturing ',
'Offices of Real Estate Appraisers ',
'All Other Home Furnishings Stores ', 'Siding Contractors ',
'Jewelry Stores ',
'Other Electronic and Precision Equipment Repair and Maintenance ',
'Institutional Furniture Manufacturing ', 'Florists ',
'Motor Vehicle Towing', 'All Other Specialty Trade Contractors',
'Office Furniture (except Wood) Manufacturing ',
'Custom Architectural Woodwork and Millwork Manufacturing ',
'Postal Service', 'Other Warehousing and Storage',
'Offices of Optometrists',
'All Other Miscellaneous Waste Management Services ',
'Other Residential Care Facilities ',
'Inland Water Freight Transportation ',
'Parking Lots and Garages ',
'Colleges, Universities, and Professional Schools ',
'Family Planning Centers ', 'Human Rights Organizations ',
'Automotive Oil Change and Lubrication Shops ',
'Confectionery Manufacturing from Purchased Chocolate ',
'Linen Supply ', 'Other Home Furnishings Stores ', 'Marinas',
'General Automotive Repair ',
'All Other Transit and Ground Passenger Transportation ',
'Household Appliance Stores ',
'Toy and Hobby Goods and Supplies Merchant Wholesalers ',
'Musical Instrument and Supplies Stores ',
'Electrical Apparatus and Equipment, Wiring Supplies, and Related Equipment Merchant Wholesalers ',
'Lessors of Residential Buildings and Dwellings ',
"Women's, Children's, and Infants' Clothing and Accessories Merchant Wholesalers ",
'Psychiatric and Substance Abuse Hospitals ',
'Hardware Merchant Wholesalers ',
'Commercial Printing (except Screen and Books) ',
'Interurban and Rural Bus Transportation',
'Other Automotive Mechanical and Electrical Repair and Maintenance ',
'Art Dealers ',
'All Other Miscellaneous Ambulatory Health Care Services ',
'Automotive Transmission Repair ',
'Other Personal and Household Goods Repair and Maintenance ',
'Passenger Car Rental and Leasing ', 'Business Associations ',
'Meat and Meat Product Merchant Wholesalers ', 'Barber Shops ',
'Clothing Accessories Stores ', 'Residential Remodelers ',
'Environment, Conservation and Wildlife Organizations ',
'Refrigerated Warehousing and Storage',
'Outpatient Mental Health and Substance Abuse Centers ',
'Fruit and Vegetable Markets ', 'Pharmacies and Drug Stores ',
'All Other Automotive Repair and Maintenance ',
'Other Chemical and Allied Products Merchant Wholesalers ',
'Offices of Chiropractors ', 'Cosmetology and Barber Schools ',
'Offices of All Other Miscellaneous Health Practitioners ',
'Paint and Wallpaper Stores ', 'Rail Transportation ',
'Automotive Parts and Accessories Stores ',
'Blood and Organ Banks ',
'Industrial Supplies Merchant Wholesalers',
'Hair, Nail, and Skin Care Services ',
'Landscape Architectural Services', 'Industrial Launderers ',
'Women’s, Girls’, and Infants’ Cut and Sew Apparel Manufacturing ',
'Food (Health) Supplement Stores ',
'Wholesale Trade Agents and Brokers ',
'Other Technical and Trade Schools ',
'All Other Professional, Scientific, and Technical Services',
'Convenience Stores ', 'Funeral Homes and Funeral Services ',
'Communication Equipment Repair and Maintenance ',
'Investment Advice ',
'Other Heavy and Civil Engineering Construction ',
'Plumbing, Heating, and Air-Conditioning Contractors ',
'Golf Courses and Country Clubs ', 'Courts ',
'Specialty (except Psychiatric and Substance Abuse) Hospitals ',
'Jewelry, Watch, Precious Stone, and Precious Metal Merchant Wholesalers ',
'Offices of Podiatrists ', 'All Other Outpatient Care Centers ',
'Other Grocery and Related Products Merchant Wholesalers ',
'Optical Goods Stores ',
'Medical, Dental, and Hospital Equipment and Supplies Merchant Wholesalers ',
'Automotive Repair and Maintenance ',
'Monetary Authorities-Central Bank', 'Home Centers ',
'Animal (except Poultry) Slaughtering ',
'All Other Telecommunications ', 'Direct Mail Advertising',
'Apple Orchards ', 'Child Day Care Services ',
'Lessors of Nonresidential Buildings (except Miniwarehouses) ',
'Packaged Frozen Food Merchant Wholesalers ',
'Educational Support Services',
'Painting and Wall Covering Contractors',
'All Other Miscellaneous Manufacturing ',
'Footwear and Leather Goods Repair', 'Gasoline Stations ',
'Residential Property Managers ']

export const topics =["PARKING","PRICE","STAFF","CLEANLINESS","ATMOSPHERE","CROWDEDNESS","PUBLIC TRANSPORTATION"]