"""empty message

Revision ID: 76ab065e727d
Revises: 
Create Date: 2020-06-16 16:38:18.918844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76ab065e727d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trader_stocks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trader_stocks',
    sa.Column('trader_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('stock_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['stock_code'], ['stock.code'], name='trader_stocks_stock_code_fkey'),
    sa.ForeignKeyConstraint(['trader_id'], ['trader.id'], name='trader_stocks_trader_id_fkey'),
    sa.PrimaryKeyConstraint('trader_id', 'stock_code', name='trader_stocks_pkey')
    )
    # ### end Alembic commands ###
